### ISSUE TITLE
Contact and About section have inconsistent padding

### ISSUE THREAD

**Issue by RyanRussell00** [Sudnisha/Sudnisha#18]
![image](https://user-images.githubusercontent.com/35180491/97040335-a23e5f00-1522-11eb-9c39-e7069abc8c2d.png)

**Comment by Sudnisha** [comment]
Fixed

**Comment by RyanRussell00** [comment]
Contact section is running over into the next section.
![image](https://user-images.githubusercontent.com/35180491/97060327-dd06be00-1547-11eb-824b-c11f80e0b8e7.png)

**Comment by Sudnisha** [comment]
I don't see any changes in my screen.
![Screenshot 2020-10-24 122702](https://user-images.githubusercontent.com/64171467/97087005-d2eec900-15f4-11eb-88ea-08816df72592.png)
