### ISSUE TITLE
Mobile-view is missing text-content for each section

### ISSUE THREAD

**Issue by RyanRussell00** [Sudnisha/Sudnisha#20]
I just noticed this issue, but it seems like the mobile-view of the website is missing the text content for all the sections. 
Also, on mobile-view there is only 1 reference showing, but on desktop view there are 2.
![image](https://user-images.githubusercontent.com/35180491/97060268-adf04c80-1547-11eb-88b9-8d1da6180f6e.png)

**Comment by Sudnisha** [comment]
Fixed
