### ISSUE TITLE
Mobile view has horizontal scroll

### ISSUE THREAD

**Issue by RyanRussell00** [Sudnisha/Sudnisha#21]

**Comment by Sudnisha** [comment]
I did not see horizontal scroll on my screen

**Comment by RyanRussell00** [comment]
For some reason on my side, the `.resume` class has `width: 600px` even on mobile and it's causing the horizontal scroll. If you can remove this style for mobile-view I believe it should fix the issue.
I believe it's line 9 of your CSS that is setting the width. So in your media query on line 214, you need to set `width: auto`

This is what I'm currently seeing on mobile:
![image](https://user-images.githubusercontent.com/35180491/97114040-684c9480-16ab-11eb-81b8-24bbb17bcdbb.png)

**Comment by RyanRussell00** [comment]
Another issue with the horizontal scroll: Your text-content is too wide and it's causing a little bit of a horizontal scroll. See how the "S" is going out of the screen here:
![image](https://user-images.githubusercontent.com/35180491/97114222-7818a880-16ac-11eb-8ab1-458648a86782.png)

I found a simple fix for this: 
In the `.responsive h2` class for the h2 (such as "Openclassrooms Web Developer", remove the `padding-inline-start`. And in the `.responsive p` class, remove the `bottom` style. This should fix that issue.

**Comment by Sudnisha** [comment]
Fixed
